### ISSUE TITLE
Installation Fails on WindowsXP and Windows 7

### ISSUE THREAD

**Issue by GoogleCodeExporter** [BackupGGCode/pyueye#3]
```
GCC build fails when executing:

python setup.py install build --compiler=mingw32 

C:\MinGW32-xy\bin\gcc.exe -mno-cygwin -mdll -O -Wall -I. -IC:\Python27\include 
-IC:\Python27\PC -c ueye\constants.c -o 
build\temp.win32-2.7\Release\ueye\constants.o None

On both Windows XP and Windows 7 systems. Running Python 2.7.3 with Cython 
0.17.2-2



```

Original issue reported on code.google.com by `Ca5u5usu...@gmail.com` on 11 Feb 2013 at 6:43

**Comment by shapecoder** [comment]
I'm trying to install the latest version on a 64-bit Windows 10 machine with 64-bit Python without success. I had to alter setup.py for usage with Python 3 (brackets around print statements), i removed the commands import and added the lib and include dirs in the include_dirs list. Still getting errors:

```ueye\ueye.pyx: cannot find cimported module 'stdlib'
ueye\ueye.pyx: cannot find cimported module 'python_cobject'
Compiling ueye\ueye.pyx because it changed.
Compiling ueye\ueyeh.pyx because it changed.
[1/2] Cythonizing ueye\ueye.pyx

Error compiling Cython file:
------------------------------------------------------------
...
#
# Author: Ricardo Amezquita Orozco <ramezquitao@cihologramas.com>


# Functions definition
from stdlib cimport *
^
------------------------------------------------------------

ueye\ueye.pyx:36:0: 'stdlib.pxd' not found

Error compiling Cython file:
------------------------------------------------------------
...
# Author: Ricardo Amezquita Orozco <ramezquitao@cihologramas.com>


# Functions definition
from stdlib cimport *
from python_cobject cimport *
^
------------------------------------------------------------

ueye\ueye.pyx:37:0: 'python_cobject.pxd' not found
warning: ueye\ueye.pyx:2681:20: Non-trivial type declarators in shared declaration (e.g. mix of pointers and values). Each pointer declaration should be on its own line.

Error compiling Cython file:
------------------------------------------------------------
...

        #Set colormode and assign image memory. The image memory assigment is done
        #in SetColorMode

        self.BufCount = bufCount
        self.BufIds = <int *>calloc(bufCount, sizeof(int))
                                  ^
------------------------------------------------------------

ueye\ueye.pyx:438:35: undeclared name not builtin: calloc

Error compiling Cython file:
------------------------------------------------------------
...

        #Set colormode and assign image memory. The image memory assigment is done
        #in SetColorMode

        self.BufCount = bufCount
        self.BufIds = <int *>calloc(bufCount, sizeof(int))
                     ^
------------------------------------------------------------

ueye\ueye.pyx:438:22: Casting temporary Python object to non-numeric non-Python type

Error compiling Cython file:
------------------------------------------------------------
...

        #Set colormode and assign image memory. The image memory assigment is done
        #in SetColorMode

        self.BufCount = bufCount
        self.BufIds = <int *>calloc(bufCount, sizeof(int))
                     ^
------------------------------------------------------------

ueye\ueye.pyx:438:22: Python objects cannot be cast to pointers of primitive types

Error compiling Cython file:
------------------------------------------------------------
...

        #Set colormode and assign image memory. The image memory assigment is done
        #in SetColorMode

        self.BufCount = bufCount
        self.BufIds = <int *>calloc(bufCount, sizeof(int))
                     ^
------------------------------------------------------------

ueye\ueye.pyx:438:22: Storing unsafe C derivative of temporary Python reference

Error compiling Cython file:
------------------------------------------------------------
...
        #Set colormode and assign image memory. The image memory assigment is done
        #in SetColorMode

        self.BufCount = bufCount
        self.BufIds = <int *>calloc(bufCount, sizeof(int))
        self.Imgs = <char **>calloc(bufCount, sizeof(char*))
                   ^
------------------------------------------------------------

ueye\ueye.pyx:439:20: Casting temporary Python object to non-numeric non-Python type

Error compiling Cython file:
------------------------------------------------------------
...
        #Set colormode and assign image memory. The image memory assigment is done
        #in SetColorMode

        self.BufCount = bufCount
        self.BufIds = <int *>calloc(bufCount, sizeof(int))
        self.Imgs = <char **>calloc(bufCount, sizeof(char*))
                   ^
------------------------------------------------------------

ueye\ueye.pyx:439:20: Python objects cannot be cast to pointers of primitive types

Error compiling Cython file:
------------------------------------------------------------
...
        #Set colormode and assign image memory. The image memory assigment is done
        #in SetColorMode

        self.BufCount = bufCount
        self.BufIds = <int *>calloc(bufCount, sizeof(int))
        self.Imgs = <char **>calloc(bufCount, sizeof(char*))
                   ^
------------------------------------------------------------

ueye\ueye.pyx:439:20: Storing unsafe C derivative of temporary Python reference

Error compiling Cython file:
------------------------------------------------------------
...
        Return Value:
        =============
        eeprom: Depending on "raw" parameter, either a list or a 'bytes' string
                containing the user EEPROM.
        '''
        cdef char *c_eeprom = <char*>calloc( 64, sizeof(char) )
                             ^
------------------------------------------------------------

ueye\ueye.pyx:743:30: Casting temporary Python object to non-numeric non-Python type

Error compiling Cython file:
------------------------------------------------------------
...
        Return Value:
        =============
        eeprom: Depending on "raw" parameter, either a list or a 'bytes' string
                containing the user EEPROM.
        '''
        cdef char *c_eeprom = <char*>calloc( 64, sizeof(char) )
            ^
------------------------------------------------------------

ueye\ueye.pyx:743:13: Storing unsafe C derivative of temporary Python reference

Error compiling Cython file:
------------------------------------------------------------
...
                count += 1

        if count + addr > 64:
            raise Exception( "Attempted to write past end of 64-byte EEPROM." )

        cdef char *c_eeprom = <char*>calloc( 64, sizeof(char) )
                             ^
------------------------------------------------------------

ueye\ueye.pyx:788:30: Casting temporary Python object to non-numeric non-Python type

Error compiling Cython file:
------------------------------------------------------------
...
                count += 1

        if count + addr > 64:
            raise Exception( "Attempted to write past end of 64-byte EEPROM." )

        cdef char *c_eeprom = <char*>calloc( 64, sizeof(char) )
            ^
------------------------------------------------------------

ueye\ueye.pyx:788:13: Storing unsafe C derivative of temporary Python reference
Traceback (most recent call last):
  File "setup.py", line 60, in <module>
    ext_modules=cythonize(extensions),
  File "C:\Users\me\AppData\Local\Programs\Python\Python36\lib\site-packages\Cython\Build\Dependencies.py", line 934, in cythonize
    cythonize_one(*args)
  File "C:\Users\me\AppData\Local\Programs\Python\Python36\lib\site-packages\Cython\Build\Dependencies.py", line 1056, in cythonize_one
    raise CompileError(None, pyx_file)
Cython.Compiler.Errors.CompileError: ueye\ueye.pyx
```

Ideas anybody?
